version: '3.2'

services:
    postgres:
        image: postgres:alpine
        expose:
            - 5432
        env_file:
            - .env
        environment:
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD

            TZ: $TIMEZONE
        volumes:
            - ./postgres-data:/var/lib/postgresql/data/

    kucid:
        image: kucid:new
        build: .
        depends_on:
            - postgres

volumes:
    postgres-data:

